"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
# config/settings.py の最上部に追加

import os
import dj_database_url
from dotenv import load_dotenv # 追加
import stripe # Stripeを使用する場合

# 環境変数を読み込む
load_dotenv() # 追加

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-hxdrd6j_*=s=7@wkq184=k##mr720wvk1b_*8qql90n_ggo)n^'

# 環境変数からSECRET_KEYを取得
SECRET_KEY = os.environ.get('SECRET_KEY', 'default-insecure-key-for-local')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 環境変数には 'host1,host2,host3' の形式で設定します。
ALLOWED_HOSTS_ENV = os.environ.get('ALLOWED_HOSTS')

if ALLOWED_HOSTS_ENV:
    ALLOWED_HOSTS = ALLOWED_HOSTS_ENV.split(',')
else:
    # デフォルトのローカル設定
    ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'lifesafetyguarantee.fly.dev']

# 開発中は以下のように設定してデバッグ情報を確認しても良い
# DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# -----------------------------------------------------------
# 💡 認証バックエンドの設定 💡
# -----------------------------------------------------------
AUTHENTICATION_BACKENDS = [
    # カスタム認証バックエンドを最初に指定
    'accounts.backends.SalesforceBackend', 
    'suppliers.backends.AgencySalesforceBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# -----------------------------------------------------------
# 💡 Stripe APIキーの設定 (動的決済リンク用) 💡
# -----------------------------------------------------------
STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY')
if STRIPE_SECRET_KEY:
    stripe.api_key = STRIPE_SECRET_KEY

STRIPE_SUBSCRIPTION_PRICE_ID = os.environ.get('STRIPE_PRICE_ID', 'price_default')

# Application definition

# config/settings.py

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # --- ここから追加 ---
    'django.contrib.sites', # 💡 追加 💡
    'widget_tweaks',
    'accounts',
    'suppliers',
    'django_extensions', # ここに追加
    'django_summernote', # 追加
    # --- ここまで追加 ---
]
# 💡 SITE_ID を追加 💡
SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # 💡 ここに追加
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], # 変更
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# 2. Renderの環境変数からデータベースURLを取得
# Render環境ではDATABASE_URLが自動で設定されます。
# ローカルでテストする場合は .env ファイルなどでこの環境変数を設定します。
DATABASE_URL = os.environ.get('DATABASE_URL')

if DATABASE_URL:
    DATABASES['default'] = dj_database_url.config(
        default=DATABASE_URL,
        conn_max_age=600, # この行は残します
    )
    # PostgreSQLを使用するため、静的ファイル関連で必要になる設定
    # 詳細は Render Django デプロイガイドを参照してください
    DATABASES['default']['OPTIONS'] = {
        'sslmode': 'require',
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# ローカルで静的ファイルを配信するための設定（通常はプロジェクトルートのstaticを指す）
STATICFILES_DIRS = [
    BASE_DIR / 'static', # 💡 staticフォルダがプロジェクトルートにあるならこれを追加
]

# config/settings.py
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') 
# ↑ この設定が必須です。

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ログイン成功後のリダイレクト先 (accounts/urls.pyで定義した名前)
LOGIN_REDIRECT_URL = 'home' 

# ログアウト後のリダイレクト先 (今回はログインページに戻す)
LOGOUT_REDIRECT_URL = 'login' 

# ログインしていないユーザーがアクセスした場合にリダイレクトされるログインURL
LOGIN_URL = 'login'

# config/settings.py (ファイル末尾などに追記)
AUTH_USER_MODEL = 'accounts.CustomUser'

# config/settings.py

# -----------------------------------------------------------
# 💡 ホスト設定の整理 💡
# -----------------------------------------------------------

# 1. 環境変数からカンマ区切りで取得
ALLOWED_HOSTS_ENV = os.environ.get('ALLOWED_HOSTS')

if ALLOWED_HOSTS_ENV:
    # 環境変数があれば、それを使用
    ALLOWED_HOSTS = ALLOWED_HOSTS_ENV.split(',')
else:
    # 環境変数がない場合のデフォルト設定
    ALLOWED_HOSTS = [
        'lifesafetyguarantee.fly.dev', # 💡 Fly.ioのドメインを確実に追加
        '127.0.0.1', 
        'localhost', 
    ]

# 2. Render向け（Renderを使っていないなら削除して良い）
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# 3. デバッグ時の '*' を安全に設定
if DEBUG and '*' not in ALLOWED_HOSTS:
    # 開発環境でデバッグ情報を確認する際に便利なように追加 (オプション)
    # 🚨 本番環境では絶対に '*' を使ってはいけません
    ALLOWED_HOSTS.append('0.0.0.0')

# -----------------------------------------------------------
# 💡 CSRF 設定 💡
# -----------------------------------------------------------

# CSRF_TRUSTED_ORIGINS: 信頼できるドメインを設定します。
# HTTPSを使用しているため、スキーマを含めることを推奨します。
CSRF_TRUSTED_ORIGINS = [
    'https://lifesafetyguarantee.fly.dev',
    # 必要であれば、ローカル環境も追加
    'http://localhost:8000', 
    'http://127.0.0.1:8000',
    'https://life-okinawa.my.salesforce.com',
]


# メディアファイルの設定（画像アップロードなどに必要）
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Summernoteの設定 (iframeを使わない設定にするとBootstrapと競合しにくい)
SUMMERNOTE_CONFIG = {
    'iframe': True,
    'summernote': {
        'width': '100%',
        'height': '400',
    }
}


# config/settings.py (メール関連の設定)

# 💡 サイトのドメイン名とプロトコルの設定 💡
# 公開ドメイン、またはローカルホスト（http）を使用
DOMAIN = '127.0.0.1:8000' # ローカルテスト用。公開デプロイ時は 'lifesafetyguarantee.fly.dev' にする
SITE_NAME = '会員サイト'

# 外部プロキシ（Fly.ioなど）を使用している場合は必須
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# 💡 開発環境用: メールをターミナルに出力する設定 💡
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# iframeを使用している場合、iframe内の表示を許可する
X_FRAME_OPTIONS = 'SAMEORIGIN' 
# ↑ この設定を「SAMEORIGIN」に変更してください。

# Salesforce 接続情報 (環境変数として設定してください)
SF_INSTANCE_URL = os.environ.get('SF_INSTANCE_URL') # 例: https://yourdomain.my.salesforce.com
SF_CLIENT_ID = os.environ.get('SF_CLIENT_ID')
SF_CLIENT_SECRET = os.environ.get('SF_CLIENT_SECRET')

STRIPE_WEBHOOK_SECRET = os.environ.get('STRIPE_WEBHOOK_SECRET')

VAPID_PUBLIC_KEY = 'BBuYPYX9LFJik5msd8w5Rnhf5d0jj4DKpu9klmkDBqq0DhilLK9FyiZ8KAFymZTk830JUFayUF_k0raG9o1XEM8'
VAPID_PRIVATE_KEY = 'erdqpRXihfjvCkLhOM_HxmttIDaev2lvf2Ww01VFVhY'
VAPID_ADMIN_EMAIL = 'mailto:k-kishimoto@life-okinawa.jp' # あなたのメールアドレス

DEFAULT_AUTO_EMAIL = '自分のメールアドレス@gmail.com'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = '自分のメールアドレス@gmail.com'
EMAIL_HOST_PASSWORD = '自分のパスワード'